import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { CairnPaths } from "../paths.js";
import type { MemoryStore } from "../stores/memory-store.js";
import type { StateStore } from "../stores/state-store.js";
import type { MemoryEntry } from "../schemas/index.js";
import { approxTokens } from "../tokens.js";

const VIEWS_HEADER = (source: string) =>
    `<!--\nGenerated by Cairn. Do not edit manually.\nSource: ${source}\nLast generated: ${new Date().toISOString()}\n-->\n\n`;

const OUTPUT_TOKEN_TARGET = 500;
const OUTPUT_TOKEN_HARD_LIMIT = 800;
const DOMAIN_TOKEN_TARGET = 300;
const DOMAIN_TOKEN_HARD_LIMIT = 500;

export class ViewsEngine {
    constructor(
        private paths: CairnPaths,
        private memoryStore: MemoryStore,
        private stateStore: StateStore,
    ) {}

    regenerate(): void {
        mkdirSync(this.paths.viewsDir, { recursive: true });
        mkdirSync(this.paths.viewsDomainsDir, { recursive: true });

        const memories = this.memoryStore.findActive();
        const state = this.stateStore.load();

        this.generateOutputMd(memories, state.stage);
        this.generateStageMd(state.stage);

        const domains = new Set(memories.map((m) => m.domain));
        for (const domain of domains) {
            const domainMemories = memories.filter(
                (m) => m.domain === domain,
            );
            this.generateDomainMd(domain, domainMemories);
        }
    }

    private generateOutputMd(
        memories: MemoryEntry[],
        stage: { phase: string; confidence: number; status: string },
    ): void {
        const sections: string[] = [];

        // Stage
        sections.push(
            `## stage\n\nphase: ${stage.phase}\nconfidence: ${stage.confidence}\nstatus: ${stage.status}`,
        );

        // No-go
        const noGoEntries = memories.filter(
            (m) =>
                m.scope === "global" ||
                m.behavior_effect.type === "avoid_suggestion",
        );
        if (noGoEntries.length > 0) {
            const items = noGoEntries
                .map(
                    (m) =>
                        `- ${m.subject.name}: ${m.behavior_effect.instruction}`,
                )
                .join("\n");
            sections.push(`## no-go\n\n${items}`);
        } else {
            sections.push(`## no-go\n\n(none)`);
        }

        // Stack
        const stackEntries = memories.filter(
            (m) => m.type === "decision" && m.status === "active",
        );
        if (stackEntries.length > 0) {
            const items = stackEntries
                .map((m) => `- ${m.subject.name}: ${m.summary}`)
                .join("\n");
            sections.push(`## stack\n\n${items}`);
        }

        // Debt
        const debtEntries = memories.filter((m) => m.type === "debt");
        if (debtEntries.length > 0) {
            const items = debtEntries
                .map((m) => `- ${m.subject.name}: ${m.summary}`)
                .join("\n");
            sections.push(`## debt\n\n${items}`);
        }

        // Hooks
        const domains = [...new Set(memories.map((m) => m.domain))];
        if (domains.length > 0) {
            const items = domains.map((d) => `- ${d}`).join("\n");
            sections.push(`## hooks\n\n${items}`);
        }

        let content =
            VIEWS_HEADER(".cairn/memory/*.yaml") + sections.join("\n\n");

        // Token control
        if (approxTokens(content) > OUTPUT_TOKEN_HARD_LIMIT) {
            content = this.truncatePreservingPriority(
                content,
                noGoEntries,
                OUTPUT_TOKEN_HARD_LIMIT,
            );
        }

        writeFileSync(join(this.paths.viewsDir, "output.md"), content, "utf-8");
    }

    private generateDomainMd(
        domain: string,
        memories: MemoryEntry[],
    ): void {
        const sections: string[] = [];
        sections.push(`# ${domain}`);

        // Trajectory
        const sorted = [...memories].sort(
            (a, b) => a.created_at.localeCompare(b.created_at),
        );
        if (sorted.length > 0) {
            const items = sorted
                .map((m) => `- [${m.created_at.slice(0, 10)}] ${m.summary}`)
                .join("\n");
            sections.push(`## trajectory\n\n${items}`);
        }

        // Rejected paths
        const rejections = memories.filter((m) => m.type === "rejection");
        if (rejections.length > 0) {
            const items = rejections
                .map(
                    (m) =>
                        `- **${m.rejected?.what ?? m.subject.name}**: ${m.rejected?.reason ?? m.summary}` +
                        (m.revisit.when.length > 0
                            ? `\n  Re-evaluate when: ${m.revisit.when.join("; ")}`
                            : ""),
                )
                .join("\n");
            sections.push(`## rejected paths\n\n${items}`);
        }

        // Known pitfalls
        const pitfalls = memories.filter(
            (m) => m.behavior_effect.type === "warn_before",
        );
        if (pitfalls.length > 0) {
            const items = pitfalls
                .map(
                    (m) =>
                        `- ${m.subject.name}: ${m.behavior_effect.instruction}`,
                )
                .join("\n");
            sections.push(`## known pitfalls\n\n${items}`);
        }

        // Open questions
        const openQuestions = memories.filter(
            (m) => m.revisit.status === "possibly_met",
        );
        if (openQuestions.length > 0) {
            const items = openQuestions
                .map(
                    (m) =>
                        `- ${m.subject.name}: revisit conditions may be met`,
                )
                .join("\n");
            sections.push(`## open questions\n\n${items}`);
        }

        let content =
            VIEWS_HEADER(`.cairn/memory/*.yaml (domain: ${domain})`) +
            sections.join("\n\n");

        if (approxTokens(content) > DOMAIN_TOKEN_HARD_LIMIT) {
            content = content.slice(0, DOMAIN_TOKEN_HARD_LIMIT * 4);
        }

        writeFileSync(
            join(this.paths.viewsDomainsDir, `${domain}.md`),
            content,
            "utf-8",
        );
    }

    private generateStageMd(stage: {
        phase: string;
        confidence: number;
        status: string;
        evidence?: Array<{ source: string; signal: string }>;
        guidance?: string[];
    }): void {
        const sections: string[] = [];
        sections.push(`# Stage Advisory`);
        sections.push(
            `**Phase**: ${stage.phase}\n**Confidence**: ${stage.confidence}\n**Status**: ${stage.status}`,
        );

        if (stage.evidence && stage.evidence.length > 0) {
            const items = stage.evidence
                .map((e) => `- [${e.source}] ${e.signal}`)
                .join("\n");
            sections.push(`## evidence\n\n${items}`);
        }

        if (stage.guidance && stage.guidance.length > 0) {
            const items = stage.guidance.map((g) => `- ${g}`).join("\n");
            sections.push(`## guidance\n\n${items}`);
        }

        const content =
            VIEWS_HEADER(".cairn/state.yaml") + sections.join("\n\n");

        writeFileSync(
            join(this.paths.viewsDir, "stage.md"),
            content,
            "utf-8",
        );
    }

    private truncatePreservingPriority(
        content: string,
        priorityEntries: MemoryEntry[],
        tokenLimit: number,
    ): string {
        // Keep header + no-go + stage, truncate the rest
        const lines = content.split("\n");
        const result: string[] = [];
        let inNoGo = false;
        let inStage = false;

        for (const line of lines) {
            if (line.startsWith("## no-go")) inNoGo = true;
            else if (line.startsWith("## stage")) inStage = true;
            else if (line.startsWith("## ")) {
                inNoGo = false;
                inStage = false;
            }

            if (
                inNoGo ||
                inStage ||
                line.startsWith("<!--") ||
                line.startsWith("-->") ||
                line === ""
            ) {
                result.push(line);
            } else if (approxTokens(result.join("\n") + "\n" + line) < tokenLimit) {
                result.push(line);
            }
        }

        return result.join("\n");
    }
}
