import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { BloodStore, SkeletonStore, DomainStore, DnaStore, StateStore, DnaStagedStore, StagedStore, SignalStore } from "../stores/index.js";
import { approxTokens } from "../tokens.js";
import { VIEWS_TOKEN_TARGETS } from "../constants.js";

function truncateToTokenLimit(text: string, hardLimit: number): string {
    if (approxTokens(text) <= hardLimit) return text;
    const charLimit = hardLimit * 4;
    return text.slice(0, charLimit) + "\n\n<!-- truncated -->\n";
}

export class ViewsEngine {
    constructor(
        private readonly bloodStore: BloodStore,
        private readonly skeletonStore: SkeletonStore,
        private readonly domainStore: DomainStore,
        private readonly dnaStore: DnaStore,
        private readonly stateStore: StateStore,
        private readonly viewsOutputPath: string,
        private readonly viewsStagePath: string,
        private readonly viewsDomainsDir: string,
        private readonly dnaStagedStore?: DnaStagedStore,
        private readonly stagedStore?: StagedStore,
        private readonly signalStore?: SignalStore,
    ) {}

    async regenerate(): Promise<void> {
        await mkdir(this.viewsDomainsDir, { recursive: true });

        const [state, allEvents, skeletonNodes, domains] = await Promise.all([
            this.stateStore.load(),
            this.bloodStore.findActive(),
            this.skeletonStore.loadAll(),
            this.domainStore.listDomains(),
        ]);

        const now = new Date().toISOString();
        const stage = state.stage;

        let output = `<!-- Generated by Cairn. Do not edit manually. Source: .cairn/{blood,skeleton,domains,dna}. Last generated: ${now} -->\n\n`;

        output += `## Stage\n\n`;
        output += `- **Phase**: ${stage.phase}\n`;
        output += `- **Confidence**: ${stage.confidence}\n`;
        if (stage.guidance.length > 0) {
            output += `- **Guidance**:\n`;
            for (const g of stage.guidance) {
                output += `  - ${g}\n`;
            }
        }
        output += `\n`;

        const noGoEvents = allEvents.filter(e => e.behavior_effect.type === "avoid_suggestion");
        output += `## No-Go\n\n`;
        if (noGoEvents.length === 0) {
            output += `_None_\n`;
        } else {
            for (const e of noGoEvents) {
                output += `- **${e.subject.name}**: ${e.behavior_effect.instruction} (${e.id})\n`;
            }
        }
        output += `\n`;

        const archDecisions = allEvents.filter(e =>
            e.type === "architecture_decision"
            && e.domain !== "global"
            && e.trigger !== "constraint"
        );
        output += `## Architecture\n\n`;
        if (archDecisions.length === 0) {
            output += `_None_\n`;
        } else {
            for (const e of archDecisions) {
                const detail = e.subject.name === e.decision_or_change
                    ? e.reasoning
                    : e.decision_or_change;
                output += `- **${e.subject.name}**: ${detail}\n`;
            }
        }
        output += `\n`;

        const behavioral = allEvents.filter(e =>
            e.type === "architecture_decision"
            && (e.domain === "global" || e.trigger === "constraint")
        );
        output += `## Behavioral Constraints\n\n`;
        if (behavioral.length === 0) {
            output += `_None_\n`;
        } else {
            for (const e of behavioral) {
                const detail = e.behavior_effect.instruction || e.decision_or_change;
                output += `- **${e.subject.name}**: ${detail}\n`;
            }
        }
        output += `\n`;

        output += `## Active Debt\n\n`;
        let hasDebt = false;
        for (const domain of domains) {
            const debt = await this.domainStore.loadAcceptedDebt(domain);
            for (const d of debt.debts) {
                hasDebt = true;
                output += `- [${domain}] ${d.what} — ${d.reason}\n`;
            }
        }
        if (!hasDebt) {
            output += `_None_\n`;
        }
        output += `\n`;

        output += `## Constraints\n\n`;
        let hasConstraints = false;
        for (const domain of domains) {
            const constraints = await this.domainStore.loadConstraints(domain);
            for (const c of constraints.constraints) {
                hasConstraints = true;
                output += `- [${domain}] ${c.what} — ${c.reason} (${c.gravity})\n`;
            }
        }
        if (!hasConstraints) {
            output += `_None_\n`;
        }
        output += `\n`;

        if (this.dnaStagedStore) {
            const pendingDna = await this.dnaStagedStore.findPending();
            if (pendingDna.length > 0) {
                output += `## Emerging DNA\n\n`;
                for (const c of pendingDna) {
                    output += `- **${c.trait_name}** (${c.level}, confidence ${c.confidence.toFixed(2)}, ${c.evidence_events.length} evidence): ${c.reasoning}\n`;
                }
                output += `\n`;
            }
        }

        if (this.stagedStore) {
            const pending = await this.stagedStore.findPending();
            output += `## Pending Review\n\n`;
            if (pending.length === 0) {
                output += `_None_\n`;
            } else {
                output += `- **Total**: ${pending.length}\n`;
                for (const entry of pending.slice(0, 8)) {
                    output += `- **${entry.id}** [${entry.draft_event.domain}/${entry.gravity}]: ${entry.draft_event.decision_or_change}\n`;
                }
                if (pending.length > 8) output += `- ... ${pending.length - 8} more\n`;
            }
            output += `\n`;
        }

        output += `## Runtime Health\n\n`;
        output += `- **Stage**: ${stage.phase} (confidence ${stage.confidence})\n`;
        output += `- **Active session**: ${state.active_session ? "yes" : "no"}\n`;
        if (this.stagedStore) {
            const allStaged = await this.stagedStore.loadAll();
            const pending = allStaged.filter(entry => entry.review_status === "pending");
            const missingEvidence = allStaged.filter(entry => !entry.draft_event.evidence).length
                + allEvents.filter(event => event.source.type !== "conversation" && !event.evidence).length;
            output += `- **Pending review**: ${pending.length}\n`;
            output += `- **Generated events missing evidence**: ${missingEvidence}\n`;
        }
        if (this.signalStore) {
            const processedSignals = await this.signalStore.loadAllProcessedSignals();
            const processedSignalIds = new Set(processedSignals.map(record => record.signal_id));
            const missingArchive = allEvents.filter(event =>
                event.evidence?.source_signal_id && !processedSignalIds.has(event.evidence.source_signal_id),
            ).length;
            output += `- **Processed signal archives**: ${processedSignals.length}\n`;
            output += `- **Generated events missing processed archive**: ${missingArchive}\n`;
        }
        if (state.session_in_progress) {
            output += `- **Incomplete session checkpoint**: ${state.session_in_progress.step}\n`;
        }
        output += `\n`;

        output += `## Hooks\n\n`;
        if (skeletonNodes.length === 0) {
            output += `_None_\n`;
        } else {
            for (const node of skeletonNodes) {
                if (node.causal_keywords.length > 0) {
                    output += `- **${node.domain}**: ${node.causal_keywords.join(", ")}\n`;
                }
            }
        }
        output += `\n`;

        output = truncateToTokenLimit(output, VIEWS_TOKEN_TARGETS.output.hardLimit);
        await writeFile(this.viewsOutputPath, output, "utf-8");

        let stageContent = `<!-- Generated by Cairn. Do not edit manually. Last generated: ${now} -->\n\n`;
        stageContent += `## Stage Advisory\n\n`;
        stageContent += `- **Phase**: ${stage.phase}\n`;
        stageContent += `- **Confidence**: ${stage.confidence}\n`;
        stageContent += `- **Status**: ${stage.status}\n\n`;

        if (stage.evidence.length > 0) {
            stageContent += `### Evidence\n\n`;
            for (const ev of stage.evidence) {
                stageContent += `- [${ev.source}] ${ev.signal}\n`;
            }
            stageContent += `\n`;
        }

        if (stage.guidance.length > 0) {
            stageContent += `### Guidance\n\n`;
            for (const g of stage.guidance) {
                stageContent += `- ${g}\n`;
            }
            stageContent += `\n`;
        }

        await writeFile(this.viewsStagePath, stageContent, "utf-8");

        for (const node of skeletonNodes) {
            let domainContent = `<!-- Generated by Cairn. Do not edit manually. Source: .cairn/{blood,skeleton,domains}. Last generated: ${now} -->\n\n`;
            domainContent += `# ${node.domain}\n\n`;
            domainContent += `**Role**: ${node.role}\n\n`;
            if (node.owns.length > 0) {
                domainContent += `**Owns**: ${node.owns.join(", ")}\n\n`;
            }
            if (node.does_not_own.length > 0) {
                domainContent += `**Does Not Own**: ${node.does_not_own.join(", ")}\n\n`;
            }

            const rejectedPaths = await this.domainStore.loadRejectedPaths(node.domain);
            domainContent += `## Rejected Paths\n\n`;
            if (rejectedPaths.paths.length === 0) {
                domainContent += `_None_\n`;
            } else {
                for (const rp of rejectedPaths.paths) {
                    domainContent += `- **${rp.path}**: ${rp.reason}\n`;
                }
            }
            domainContent += `\n`;

            const traumaEvents = await this.bloodStore.findTrauma(node.domain);
            domainContent += `## Pitfalls\n\n`;
            if (traumaEvents.length === 0) {
                domainContent += `_None_\n`;
            } else {
                for (const te of traumaEvents) {
                    domainContent += `- **${te.subject.name}**: ${te.decision_or_change}\n`;
                }
            }
            domainContent += `\n`;

            const domainEvents = allEvents
                .filter(e => e.domain === node.domain)
                .sort((a, b) => b.time.localeCompare(a.time));
            domainContent += `## Trajectory\n\n`;
            if (domainEvents.length === 0) {
                domainContent += `_No recent events_\n`;
            } else {
                for (const de of domainEvents) {
                    domainContent += `- [${de.time}] ${de.type}: ${de.decision_or_change}\n`;
                }
            }
            domainContent += `\n`;

            domainContent = truncateToTokenLimit(domainContent, VIEWS_TOKEN_TARGETS.domain.hardLimit);
            await writeFile(join(this.viewsDomainsDir, `${node.domain}.md`), domainContent, "utf-8");
        }
    }
}
